//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesCompanyApp4438
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanceCompanyEntities : DbContext
    {
        public DanceCompanyEntities()
            : base("name=DanceCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<PricePlusVAT> PricePlusVAT { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherCourse> TeacherCourse { get; set; }
        public virtual DbSet<Trainee> Trainee { get; set; }
        public virtual DbSet<TraineeCourse> TraineeCourse { get; set; }
    }
}
